package com.fsd.springmvc.util;

public interface QueryConstants {

	String INSERT_BOOK_SQL = "INSERT INTO BOOK (BOOK_ID, TITLE, PRICE, VOLUME, PUBLISH_DATE) "
			+ "VALUES (?, ?, ?, ?, ?)";
	
	String DELETE_BOOK_SQL = "DELETE FROM BOOK WHERE BOOK_ID = ?"; 
	
	String SELECT_ALL_BOOKS_SQL = "SELECT * FROM BOOK";
	
	String SELECT_BOOK_BY_BOOK_ID_SQL = "SELECT * FROM BOOK WHERE BOOK_ID = ?";
	
	String SELECT_BOOK_BY_TITLE_SQL = "SELECT * FROM BOOK WHERE TITLE = ?";
	
	String INSERT_SUBJECT_SQL = "INSERT INTO SUBJECT (SUBJECT_ID, BOOK_ID, SUBJECT_TITLE, DURATION_IN_HOURS) "
			+ "VALUES (?, ?, ?, ?)";
	
	String DELETE_SUBJECT_SQL = "DELETE FROM SUBJECT WHERE SUBJECT_ID = ?"; 
	
	String SELECT_ALL_SUBJECTS_SQL = "SELECT SUBJECT_ID, SUB.BOOK_ID BOOK_ID, SUBJECT_TITLE, DURATION_IN_HOURS,"
			+ " TITLE, PRICE, VOLUME, PUBLISH_DATE FROM SUBJECT SUB, BOOK BK WHERE SUB.BOOK_ID = BK.BOOK_ID ORDER BY SUBJECT_ID, BOOK_ID";
	
	String SELECT_SUBJECT_BY_ID_SQL = "SELECT SUBJECT_ID, SUB.BOOK_ID BOOK_ID, SUBJECT_TITLE, DURATION_IN_HOURS,"
			+ " TITLE, PRICE, VOLUME, PUBLISH_DATE FROM SUBJECT SUB, BOOK BK WHERE SUBJECT_ID = ? AND "
			+ " SUB.BOOK_ID = BK.BOOK_ID ORDER BY SUBJECT_ID, BOOK_ID";
	
	String SELECT_SUBJECT_BY_TITLE_SQL = "SELECT SUBJECT_ID, SUB.BOOK_ID BOOK_ID, SUBJECT_TITLE, DURATION_IN_HOURS,"
			+ " TITLE, PRICE, VOLUME, PUBLISH_DATE FROM SUBJECT SUB, BOOK BK WHERE SUBJECT_TITLE = ? AND "
			+ " SUB.BOOK_ID = BK.BOOK_ID ORDER BY SUBJECT_ID, BOOK_ID";
	
	String SELECT_SUBJECT_BY_BOOK_ID_SQL = "SELECT SUBJECT_ID, SUB.BOOK_ID BOOK_ID, SUBJECT_TITLE, DURATION_IN_HOURS,"
			+ " TITLE, PRICE, VOLUME, PUBLISH_DATE FROM SUBJECT SUB, BOOK BK WHERE SUB.BOOK_ID = ? AND SUB.BOOK_ID = BK.BOOK_ID";
}
